# Generated by Django 5.2.8 on 2025-11-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneterm',
            name='embedding_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
