# Generated by Django 5.2.8 on 2025-12-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
