# Generated by Django 5.2.8 on 2025-12-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_author_category_partofspeech_remove_language_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='embedding_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='definition',
            name='embedding_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
