# Generated by Django 5.2.8 on 2025-12-04 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_context_embedding_json_definition_embedding_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termtranslation',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='dictionary.droneterm'),
        ),
    ]
