# Generated by Django 5.2.8 on 2025-12-04 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_alter_termtranslation_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droneterm',
            name='language',
            field=models.ForeignKey(default='en', on_delete=django.db.models.deletion.CASCADE, to='dictionary.language'),
        ),
        migrations.AlterField(
            model_name='termtranslation',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drone_translations', to='dictionary.droneterm'),
        ),
    ]
