# Generated by Django 5.2.8 on 2025-12-04 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_alter_droneterm_language_alter_termtranslation_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droneterm',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.language'),
        ),
    ]
