# Generated by Django 5.2.8 on 2025-12-08 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_alter_droneterm_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termtranslation',
            name='term',
            field=models.ForeignKey(default=717, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='dictionary.term'),
            preserve_default=False,
        ),
    ]
